### ISSUE TITLE
Error when trying to install extension

### ISSUE THREAD

**Issue by whydakk** [andyholmes/gnome-shell-extension-scrovol#3]
Hey,
I just updated Gnome to 3.36 on Manjaro and this extension stopped working. So I just removed it from my system, then installed it again and the ERROR info has displayed. There's no way i could run it with success.
Logs:
`JS ERROR: Extension scrovol@andyholmes.github.io: TypeError: VolumeIndicator._onScrollEvent is undefined
                                             enable@/home/s4bba7/.local/share/gnome-shell/extensions/scrovol@andyholmes.github.io/extension.js:22:1
                                             _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:160:32
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:311:26
                                             callback@resource:///org/gnome/shell/ui/extensionDownloader.js:204:39
                                             gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:97:13`

**Comment by andyholmes** [comment]
That means you still have an old version of the extension installed. Only v3 supports GNOME 3.36.

**Comment by whydakk** [comment]
That was strange, but it showed v3 in Extensions app but in .local/gnome-shell/extensions there're 2 versions - with v3 and without. Remove and reinstall didn't help so i needed those steps to repair:

disable extensions, restart the system, install the srcovol (2x click ON because the switch button turned off after install), enable all the extensions from the Extensions app and it finally worked.
