### ISSUE TITLE
GNOME 3.38 Support?

### ISSUE THREAD

**Issue by Scotty-Trees** [andyholmes/gnome-shell-extension-scrovol#4]
Gnome 3.38 has been released and was hoping to see your awesome extension get updated to support the latest release, thank you!

**Comment by andyholmes** [comment]
Works for me, what's the problem?

**Comment by Scotty-Trees** [comment]
Greetings, I was just on the Gnome extensions website and saw your extension didn't appear to support Gnome 3.38 yet. I'm currently on Pop!_OS (Ubuntu based), so I should be getting an update to Gnome 3.38 (still on 3.36 atm) in the beginning of November. It's not that I currently have problem, my comment was more just like a question or rather a reminder to keep these lovely extensions like yours up to date with the latest release. My apologies I didn't really clearly say that the first time. btw, can't live without your extension, thanks very much for making it, you may close this :)
